### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by maximsamoilov** [cobaltcrm/cobalt#157]
Step: Database

index.php?task=postinstall&m=validateDb&db_drive=Mysqli&host=localhost&name=cobalt&pass=&user=root

get error in ajax response:

exception 'Joomla\DI\Exception\DependencyResolutionException' with message 'Could not resolve dependency
: options' in Z:\home\cobalt.tst\www\vendor\joomla\di\src\Container.php:256
Stack trace:
#0 Z:\home\cobalt.tst\www\vendor\joomla\di\src\Container.php(139): Joomla\DI\Container->getMethodArgs

(Object(ReflectionMethod))
#1 Z:\home\cobalt.tst\www\vendor\joomla\di\src\Container.php(238): Joomla\DI\Container->buildObject('Joomla

\Database...')
#2 Z:\home\cobalt.tst\www\vendor\joomla\di\src\Container.php(139): Joomla\DI\Container->getMethodArgs

(Object(ReflectionMethod))
#3 Z:\home\cobalt.tst\www\src\Cobalt\Factory.php(72): Joomla\DI\Container->buildObject('\Cobalt\Model

\D...')
#4 Z:\home\cobalt.tst\www\src\Cobalt\Factory.php(128): Cobalt\Factory::getModel('DefaultModel')
#5 Z:\home\cobalt.tst\www\src\Cobalt\Controller\DefaultController.php(46): Cobalt\Factory::getView('dashboard'

, 'default', 'html', Array)
#6 Z:\home\cobalt.tst\www\src\Cobalt\Application.php(392): Cobalt\Controller\DefaultController->execute

()
#7 Z:\home\cobalt.tst\www\vendor\joomla\application\src\AbstractWebApplication.php(119): Cobalt\Application-

> doExecute()
> # 8 Z:\home\cobalt.tst\www\index.php(97): Joomla\Application\AbstractWebApplication->execute()
> # 9 {main}

**Comment by xillibit** [comment]
Hello,

Did-you have used in first `composer install` to download composer dependencies ?

**Comment by maximsamoilov** [comment]
Hi, yes. I used composer install first.

I'm trying to install both Denver and the MAMP PRO. I get the same error

**Comment by maximsamoilov** [comment]
I can not find this option is $ _SERVER [ 'HTACCESS'] in php documentation(

**Comment by dbhurley** [comment]
Check your Apache ENV's should be there. :wink:
